"""empty message

Revision ID: 01db9b7249cc
Revises: 834d18bcef9b
Create Date: 2025-02-14 10:51:32.201381

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01db9b7249cc'
down_revision: Union[str, None] = '834d18bcef9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.drop_column('products', 'type')
    op.add_column('user_wishlists', sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('user_wishlists', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_wishlists', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('user_wishlists', 'created_datetime')
    op.add_column('products', sa.Column('type', postgresql.ENUM('hall', 'studio', 'dress', 'makeup', name='categorytypeenum', create_type=False), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'category_id')
    # ### end Alembic commands ###
