"""empty message

Revision ID: 0e403e679141
Revises: 8c6c092b4728
Create Date: 2025-03-06 11:03:55.102879

"""

from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e403e679141"
down_revision: Union[str, None] = "8c6c092b4728"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "tel",
        existing_type=sa.VARCHAR(length=20),
        type_=sqlmodel.sql.sqltypes.AutoString(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "fax_tel",
        existing_type=sa.VARCHAR(length=20),
        type_=sqlmodel.sql.sqltypes.AutoString(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "sido",
        existing_type=sa.VARCHAR(length=20),
        type_=sqlmodel.sql.sqltypes.AutoString(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "gugun",
        existing_type=sa.VARCHAR(length=20),
        type_=sqlmodel.sql.sqltypes.AutoString(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "dong",
        existing_type=sa.VARCHAR(length=20),
        type_=sqlmodel.sql.sqltypes.AutoString(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "subway_line",
        existing_type=sa.VARCHAR(length=20),
        type_=sqlmodel.sql.sqltypes.AutoString(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "subway_name",
        existing_type=sa.VARCHAR(length=20),
        type_=sqlmodel.sql.sqltypes.AutoString(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "subway_exit",
        existing_type=sa.VARCHAR(length=20),
        type_=sqlmodel.sql.sqltypes.AutoString(length=30),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "subway_exit",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=30),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "subway_name",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=30),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "subway_line",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=30),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "dong",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=30),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "gugun",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=30),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "sido",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=30),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "fax_tel",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=30),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "products",
        "tel",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=30),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
