"""empty message

Revision ID: 17abaaa03bfa
Revises: 34f2a46a8d7a
Create Date: 2025-05-22 15:44:01.607678

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17abaaa03bfa"
down_revision: Union[str, None] = "34f2a46a8d7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("budget", sa.Integer(), nullable=False, default=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "budget")
    # ### end Alembic commands ###
