"""empty message

Revision ID: 1bb11908b80b
Revises: 517057595500
Create Date: 2025-02-08 22:19:22.655254

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bb11908b80b'
down_revision: Union[str, None] = '517057595500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wedding_halls')
    op.drop_table('wedding_hall_reviews')
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index('ix_user_email', table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user', 'is_deleted')
    op.drop_column('user', 'is_superuser')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.create_table('wedding_hall_reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nick', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('block', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('profile_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('wedding_month', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('partner_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('my_customer_partner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_like', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('like_cnt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reply_cnt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_anonymous', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_certification', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('state', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reg_tsp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('hall_uuid', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('hall_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('card_cover_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('card_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('card_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('card_link', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('score_홀분위기', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('comment_홀분위기', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score_음식', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('comment_음식', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score_서비스', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('comment_서비스', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score_부케', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('comment_부케', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score_가격', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('comment_가격', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score_스타일', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('comment_스타일', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score_담당샘', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('comment_담당샘', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score_사진작가', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('comment_사진작가', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('wedding_halls',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('biz_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('type_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tel', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('logo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cover_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('profile', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('profile_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('regionv2', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tag_식대_최소', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tag_타입', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('tag_예식형태', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('tag_메뉴', sa.VARCHAR(length=200), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
