"""empty message

Revision ID: 26bc5ab385c7
Revises: 80b044d90714
Create Date: 2025-04-12 22:58:04.106807

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26bc5ab385c7"
down_revision: Union[str, None] = "80b044d90714"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_studios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("album_count", sa.Integer(), nullable=False),
        sa.Column("album_page_count", sa.Integer(), nullable=False),
        sa.Column("frame_count", sa.Integer(), nullable=False),
        sa.Column("include_original_data", sa.Boolean(), nullable=False),
        sa.Column("include_edited_data", sa.Boolean(), nullable=False),
        sa.Column("shooting_duration", sa.Integer(), nullable=False),
        sa.Column("outfit_count", sa.Integer(), nullable=False),
        sa.Column("dress_count", sa.Integer(), nullable=False),
        sa.Column("casual_count", sa.Integer(), nullable=False),
        sa.Column("has_garden_scene", sa.Boolean(), nullable=False),
        sa.Column("has_road_scene", sa.Boolean(), nullable=False),
        sa.Column("has_rooftop_scene", sa.Boolean(), nullable=False),
        sa.Column("has_night_scene", sa.Boolean(), nullable=False),
        sa.Column("has_hanbok_scene", sa.Boolean(), nullable=False),
        sa.Column("has_pet_scene", sa.Boolean(), nullable=False),
        sa.Column("has_black_white_scene", sa.Boolean(), nullable=False),
        sa.Column("hair_makeup_available", sa.Boolean(), nullable=False),
        sa.Column("additional_cost_info", sa.Text(), nullable=True),
        sa.Column(
            "discount_info", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column(
            "business_hours",
            sqlmodel.sql.sqltypes.AutoString(length=200),
            nullable=True,
        ),
        sa.Column("cancel_policy", sa.Text(), nullable=True),
        sa.Column("review_count", sa.Integer(), nullable=False),
        sa.Column("review_score", sa.Float(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_datetime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_datetime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_datetime", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id"),
    )
    op.add_column(
        "product_halls",
        sa.Column("has_family_waiting_room", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "product_halls",
        sa.Column("has_pyebaek_room", sa.Boolean(), nullable=False),
    )
    op.drop_column("product_halls", "contain_pyebaek_room")
    op.drop_column("product_halls", "contain_family_waiting_room")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_halls",
        sa.Column(
            "contain_family_waiting_room",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "product_halls",
        sa.Column(
            "contain_pyebaek_room", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("product_halls", "has_pyebaek_room")
    op.drop_column("product_halls", "has_family_waiting_room")
    op.drop_table("product_studios")
    # ### end Alembic commands ###
