"""empty message

Revision ID: 2e31102ed46b
Revises: 73c33dc15177
Create Date: 2025-03-08 16:26:52.140930

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e31102ed46b'
down_revision: Union[str, None] = '73c33dc15177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('wedding_datetime', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('advertising_agreement', sa.Boolean(), nullable=True))
    op.alter_column('users', 'service_policy_agreement',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'privacy_policy_agreement',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'third_party_information_agreement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('third_party_information_agreement', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('users', 'privacy_policy_agreement',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'service_policy_agreement',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('users', 'advertising_agreement')
    op.drop_column('users', 'wedding_datetime')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
