"""empty message

Revision ID: 34f2a46a8d7a
Revises: 62e1ebdcd78a
Create Date: 2025-04-29 14:50:29.905072

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f2a46a8d7a'
down_revision: Union[str, None] = '62e1ebdcd78a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklists', sa.Column('memo', sa.Text(), nullable=True))
    op.alter_column('product_halls', 'has_family_waiting_room',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('product_halls', 'has_pyebaek_room',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_halls', 'has_pyebaek_room',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('product_halls', 'has_family_waiting_room',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('checklists', 'memo')
    # ### end Alembic commands ###
