"""empty message

Revision ID: 3c5a341583a6
Revises: f0bfc31cb565
Create Date: 2025-03-05 15:27:44.106239

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c5a341583a6'
down_revision: Union[str, None] = 'f0bfc31cb565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_halls', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('product_halls', sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=True))
    op.add_column('product_halls', sa.Column('updated_datetime', sa.DateTime(timezone=True), nullable=True))
    op.add_column('product_halls', sa.Column('deleted_datetime', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('deleted_datetime', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'deleted_datetime')
    op.drop_column('product_halls', 'deleted_datetime')
    op.drop_column('product_halls', 'updated_datetime')
    op.drop_column('product_halls', 'created_datetime')
    op.drop_column('product_halls', 'is_deleted')
    # ### end Alembic commands ###
