"""empty message

Revision ID: 43dbe204086d
Revises: f17f50a7df9d
Create Date: 2025-06-27 16:41:47.862378

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43dbe204086d"
down_revision: Union[str, None] = "f17f50a7df9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_categories",
        sa.Column("icon_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_categories", "icon_url")
    # ### end Alembic commands ###
