"""empty message

Revision ID: 484763b406c4
Revises: 43d47fe7a8a5
Create Date: 2025-03-03 12:06:27.743558

"""

from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "484763b406c4"
down_revision: Union[str, None] = "43d47fe7a8a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("suggest_checklist")
    op.add_column(
        "user_checklists",
        sa.Column("is_system_checklist", sa.Boolean(), nullable=False),
    )
    op.alter_column(
        "user_checklists", "user_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_checklists", "user_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_column("user_checklists", "is_system_checklist")
    op.create_table(
        "suggest_checklist",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "checklist_category_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("display_order", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_datetime",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_datetime",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "deleted_datetime",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["checklist_category_id"],
            ["checklist_categories.id"],
            name="suggest_checklist_checklist_category_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="suggest_checklist_pkey"),
    )
    # ### end Alembic commands ###
