"""empty message

Revision ID: 5608853c56cf
Revises: 4472029fa321
Create Date: 2025-02-13 17:44:16.274276

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5608853c56cf'
down_revision: Union[str, None] = '4472029fa321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('is_ready', sa.Boolean(), nullable=False))
    op.add_column('category', sa.Column('order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'order')
    op.drop_column('category', 'is_ready')
    # ### end Alembic commands ###
