"""empty message

Revision ID: 56c8aaf41f6d
Revises: 8ba3afd9226a
Create Date: 2025-06-26 14:30:17.406387

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c8aaf41f6d'
down_revision: Union[str, None] = '8ba3afd9226a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_hall_venues', 'has_bride_room',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('product_hall_venues', 'has_pyebaek_room',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('product_hall_venues', 'has_banquet_hall',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_hall_venues', 'has_banquet_hall',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('product_hall_venues', 'has_pyebaek_room',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('product_hall_venues', 'has_bride_room',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
