"""empty message

Revision ID: 5ec15f039915
Revises: 56c8aaf41f6d
Create Date: 2025-06-26 14:36:39.785272

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ec15f039915'
down_revision: Union[str, None] = '56c8aaf41f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_blogs', 'thumbnail_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_blogs', 'thumbnail_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
