"""empty message

Revision ID: 62e1ebdcd78a
Revises: d2699a4f3773
Create Date: 2025-04-13 17:11:21.171784

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e1ebdcd78a'
down_revision: Union[str, None] = 'd2699a4f3773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_halls', 'has_family_waiting_room',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('product_halls', 'has_pyebaek_room',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('product_studios', 'dress_count')
    op.drop_column('product_studios', 'album_page_count')
    op.drop_column('product_studios', 'include_original_data')
    op.drop_column('product_studios', 'outfit_count')
    op.drop_column('product_studios', 'review_count')
    op.drop_column('product_studios', 'album_count')
    op.drop_column('product_studios', 'cancel_policy')
    op.drop_column('product_studios', 'additional_cost_info')
    op.drop_column('product_studios', 'shooting_duration')
    op.drop_column('product_studios', 'casual_count')
    op.drop_column('product_studios', 'review_score')
    op.drop_column('product_studios', 'frame_count')
    op.drop_column('product_studios', 'business_hours')
    op.drop_column('product_studios', 'include_edited_data')
    op.drop_column('product_studios', 'discount_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_studios', sa.Column('discount_info', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('product_studios', sa.Column('include_edited_data', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('product_studios', sa.Column('business_hours', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('product_studios', sa.Column('frame_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product_studios', sa.Column('review_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('product_studios', sa.Column('casual_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product_studios', sa.Column('shooting_duration', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product_studios', sa.Column('additional_cost_info', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('product_studios', sa.Column('cancel_policy', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('product_studios', sa.Column('album_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product_studios', sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product_studios', sa.Column('outfit_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product_studios', sa.Column('include_original_data', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('product_studios', sa.Column('album_page_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product_studios', sa.Column('dress_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('product_halls', 'has_pyebaek_room',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('product_halls', 'has_family_waiting_room',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
