"""empty message

Revision ID: 638c712f4077
Revises: 6f4a4e7199b9
Create Date: 2025-02-20 10:13:26.383774

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '638c712f4077'
down_revision: Union[str, None] = '6f4a4e7199b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggest_checklist', 'recommended_timeline')
    op.drop_column('user_checklists', 'deadline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_checklists', sa.Column('deadline', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('suggest_checklist', sa.Column('recommended_timeline', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
