"""empty message

Revision ID: 6aeee37b9b84
Revises: 
Create Date: 2025-04-10 16:56:22.546843

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aeee37b9b84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_categories_name'), 'product_categories', ['name'], unique=True)
    op.create_table('suggest_search_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_category_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashtag', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('direct_link', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('enterprise_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('enterprise_code', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('tel', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('fax_tel', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('sido', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('gugun', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('dong', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('subway_line', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('subway_name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('subway_exit', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('park_limit', sa.Integer(), nullable=True),
    sa.Column('park_free_hours', sa.Integer(), nullable=True),
    sa.Column('way_text', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('holiday', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('business_hours', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_ai_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('review_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_halls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('elevator_count', sa.Integer(), nullable=False),
    sa.Column('atm_count', sa.Integer(), nullable=False),
    sa.Column('contain_family_waiting_room', sa.Boolean(), nullable=False),
    sa.Column('contain_pyebaek_room', sa.Boolean(), nullable=False),
    sa.Column('valet_parking', sa.Boolean(), nullable=False),
    sa.Column('dress_room', sa.Boolean(), nullable=False),
    sa.Column('smoking_area', sa.Boolean(), nullable=False),
    sa.Column('photo_zone', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('score_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_wishlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('memo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='unique_user_product')
    )
    op.create_table('product_hall_venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_hall_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wedding_interval', sa.Integer(), nullable=False),
    sa.Column('wedding_times', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wedding_type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('hall_styles', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hall_types', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('guaranteed_min_count', sa.Integer(), nullable=False),
    sa.Column('min_capacity', sa.Integer(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('basic_price', sa.Integer(), nullable=False),
    sa.Column('peak_season_price', sa.Integer(), nullable=False),
    sa.Column('ceiling_height', sa.Integer(), nullable=False),
    sa.Column('virgin_road_length', sa.Integer(), nullable=False),
    sa.Column('include_drink', sa.Boolean(), nullable=False),
    sa.Column('include_alcohol', sa.Boolean(), nullable=False),
    sa.Column('include_service_fee', sa.Boolean(), nullable=False),
    sa.Column('include_vat', sa.Boolean(), nullable=False),
    sa.Column('bride_room_entry_methods', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bride_room_makeup_room', sa.Boolean(), nullable=False),
    sa.Column('food_menu', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('food_cost_per_adult', sa.Integer(), nullable=False),
    sa.Column('food_cost_per_child', sa.Integer(), nullable=False),
    sa.Column('banquet_hall_running_time', sa.Integer(), nullable=False),
    sa.Column('banquet_hall_max_capacity', sa.Integer(), nullable=False),
    sa.Column('additional_info', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('special_notes', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_hall_id'], ['product_halls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_hall_venues')
    op.drop_table('user_wishlists')
    op.drop_table('product_scores')
    op.drop_table('product_images')
    op.drop_table('product_halls')
    op.drop_table('product_ai_reviews')
    op.drop_table('products')
    op.drop_table('suggest_search_keywords')
    op.drop_index(op.f('ix_product_categories_name'), table_name='product_categories')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
