"""empty message

Revision ID: 79dcf8ce7f19
Revises: 17abaaa03bfa
Create Date: 2025-06-18 17:59:13.309818

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "79dcf8ce7f19"
down_revision: Union[str, None] = "17abaaa03bfa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_images", sa.Column("product_venue_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "product_images",
        sa.Column(
            "image_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
    )
    op.create_foreign_key(
        None, "product_images", "product_hall_venues", ["product_venue_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "budget", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(None, "user_spents", type_="foreignkey")
    op.create_foreign_key(
        "user_spents_category_id_fkey",
        "user_spents",
        "checklist_categories",
        ["category_id"],
        ["id"],
    )
    op.drop_constraint(None, "product_images", type_="foreignkey")
    op.drop_column("product_images", "image_type")
    op.drop_column("product_images", "product_venue_id")
    op.create_table(
        "checklist_categories",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("display_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "is_system_category", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_datetime",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_datetime",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "deleted_datetime",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="checklist_categories_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="checklist_categories_pkey"),
    )
    # ### end Alembic commands ###
