"""empty message

Revision ID: 8ba3afd9226a
Revises: 79dcf8ce7f19
Create Date: 2025-06-25 23:13:17.713227

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8ba3afd9226a"
down_revision: Union[str, None] = "79dcf8ce7f19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("checklist_categories")
    op.add_column(
        "product_hall_venues", sa.Column("has_bride_room", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "product_hall_venues",
        sa.Column("has_pyebaek_room", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "product_hall_venues",
        sa.Column("has_banquet_hall", sa.Boolean(), nullable=True),
    )
    op.alter_column(
        "product_images",
        "image_type",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column("users", "budget", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "budget", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "product_images",
        "image_type",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.drop_column("product_hall_venues", "has_banquet_hall")
    op.drop_column("product_hall_venues", "has_pyebaek_room")
    op.drop_column("product_hall_venues", "has_bride_room")
    op.create_table(
        "checklist_categories",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("display_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "is_system_category", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_datetime",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_datetime",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "deleted_datetime",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="checklist_categories_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="checklist_categories_pkey"),
    )
    # ### end Alembic commands ###
