"""empty message

Revision ID: 8c6c092b4728
Revises: 3c5a341583a6
Create Date: 2025-03-06 10:34:10.622399

"""

from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c6c092b4728"
down_revision: Union[str, None] = "3c5a341583a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column(
            "image_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_datetime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_datetime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_datetime", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "product_halls",
        sa.Column(
            "hall_type", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
    )
    op.add_column(
        "product_halls",
        sa.Column(
            "hall_style", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
    )
    op.add_column(
        "product_halls", sa.Column("guaranteed_min_count", sa.Integer(), nullable=False)
    )
    op.add_column(
        "product_halls",
        sa.Column("wedding_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column(
        "product_halls", sa.Column("wedding_running_time", sa.Integer(), nullable=False)
    )
    op.add_column(
        "product_halls",
        sa.Column(
            "food_type", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
    )
    op.add_column("product_halls", sa.Column("food_cost", sa.Integer(), nullable=False))
    op.add_column("product_halls", sa.Column("elevator", sa.Boolean(), nullable=False))
    op.add_column(
        "product_halls", sa.Column("valet_parking", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "product_halls", sa.Column("pyebaek_room", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "product_halls", sa.Column("family_waiting_room", sa.Boolean(), nullable=False)
    )
    op.add_column("product_halls", sa.Column("atm", sa.Boolean(), nullable=False))
    op.add_column(
        "product_halls", sa.Column("dress_room", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "product_halls", sa.Column("smoking_area", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "product_halls", sa.Column("photo_zone", sa.Boolean(), nullable=False)
    )
    op.drop_column("product_halls", "address")
    op.drop_column("product_halls", "longitude")
    op.drop_column("product_halls", "latitude")
    op.drop_column("product_halls", "parking_capacity")
    op.add_column(
        "products",
        sa.Column(
            "hashtag", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "direct_link", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "thumbnail", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "logo_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "enterprise_name",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "enterprise_code",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
        ),
    )
    op.add_column(
        "products",
        sa.Column("tel", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    )
    op.add_column(
        "products",
        sa.Column(
            "fax_tel", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
    )
    op.add_column(
        "products",
        sa.Column("sido", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    )
    op.add_column(
        "products",
        sa.Column("gugun", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    )
    op.add_column(
        "products",
        sa.Column("dong", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    )
    op.add_column(
        "products",
        sa.Column(
            "address", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
    )
    op.add_column("products", sa.Column("lat", sa.Float(), nullable=False))
    op.add_column("products", sa.Column("lng", sa.Float(), nullable=False))
    op.add_column(
        "products",
        sa.Column(
            "subway_line", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "subway_name", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "subway_exit", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
    )
    op.add_column("products", sa.Column("park_limit", sa.Integer(), nullable=False))
    op.add_column(
        "products", sa.Column("park_free_hours", sa.Integer(), nullable=False)
    )
    op.add_column(
        "products",
        sa.Column(
            "way_text", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "holiday", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "business_hours",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "business_hours")
    op.drop_column("products", "holiday")
    op.drop_column("products", "way_text")
    op.drop_column("products", "park_free_hours")
    op.drop_column("products", "park_limit")
    op.drop_column("products", "subway_exit")
    op.drop_column("products", "subway_name")
    op.drop_column("products", "subway_line")
    op.drop_column("products", "lng")
    op.drop_column("products", "lat")
    op.drop_column("products", "address")
    op.drop_column("products", "dong")
    op.drop_column("products", "gugun")
    op.drop_column("products", "sido")
    op.drop_column("products", "fax_tel")
    op.drop_column("products", "tel")
    op.drop_column("products", "enterprise_code")
    op.drop_column("products", "enterprise_name")
    op.drop_column("products", "logo_url")
    op.drop_column("products", "thumbnail")
    op.drop_column("products", "direct_link")
    op.drop_column("products", "hashtag")
    op.add_column(
        "product_halls",
        sa.Column(
            "parking_capacity", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "product_halls",
        sa.Column(
            "latitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "product_halls",
        sa.Column(
            "longitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "product_halls",
        sa.Column("address", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("product_halls", "photo_zone")
    op.drop_column("product_halls", "smoking_area")
    op.drop_column("product_halls", "dress_room")
    op.drop_column("product_halls", "atm")
    op.drop_column("product_halls", "family_waiting_room")
    op.drop_column("product_halls", "pyebaek_room")
    op.drop_column("product_halls", "valet_parking")
    op.drop_column("product_halls", "elevator")
    op.drop_column("product_halls", "food_cost")
    op.drop_column("product_halls", "food_type")
    op.drop_column("product_halls", "wedding_running_time")
    op.drop_column("product_halls", "wedding_type")
    op.drop_column("product_halls", "guaranteed_min_count")
    op.drop_column("product_halls", "hall_style")
    op.drop_column("product_halls", "hall_type")
    op.drop_table("product_images")
    # ### end Alembic commands ###
