"""empty message

Revision ID: 95490fa7c237
Revises: 446bc63ea4be
Create Date: 2025-02-11 18:58:58.945401

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95490fa7c237'
down_revision: Union[str, None] = '446bc63ea4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestchecklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recommended_timeline', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('defaultchecklistitem')
    op.drop_table('customchecklistitem')
    op.add_column('userchecklist', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('userchecklist', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('userchecklist', sa.Column('default_item_id', sa.Integer(), nullable=False))
    op.add_column('userchecklist', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('userchecklist', sa.Column('is_completed', sa.Boolean(), nullable=False))
    op.add_column('userchecklist', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('userchecklist', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_index('ix_userchecklist_user_id', table_name='userchecklist')
    op.create_foreign_key(None, 'userchecklist', 'suggestchecklist', ['default_item_id'], ['id'])
    op.create_foreign_key(None, 'userchecklist', 'category', ['category_id'], ['id'])
    op.drop_column('userchecklist', 'wedding_date')
    op.drop_column('userchecklist', 'created_at')
    op.drop_column('userchecklist', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userchecklist', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('userchecklist', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('userchecklist', sa.Column('wedding_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'userchecklist', type_='foreignkey')
    op.drop_constraint(None, 'userchecklist', type_='foreignkey')
    op.create_index('ix_userchecklist_user_id', 'userchecklist', ['user_id'], unique=False)
    op.drop_column('userchecklist', 'category_id')
    op.drop_column('userchecklist', 'completed_at')
    op.drop_column('userchecklist', 'is_completed')
    op.drop_column('userchecklist', 'deadline')
    op.drop_column('userchecklist', 'default_item_id')
    op.drop_column('userchecklist', 'description')
    op.drop_column('userchecklist', 'title')
    op.create_table('customchecklistitem',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('default_item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('checklist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='customchecklistitem_category_id_fkey'),
    sa.ForeignKeyConstraint(['checklist_id'], ['userchecklist.id'], name='customchecklistitem_checklist_id_fkey'),
    sa.ForeignKeyConstraint(['default_item_id'], ['defaultchecklistitem.id'], name='customchecklistitem_default_item_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='customchecklistitem_pkey')
    )
    op.create_table('defaultchecklistitem',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recommended_timeline', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='defaultchecklistitem_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='defaultchecklistitem_pkey')
    )
    op.drop_table('suggestchecklist')
    # ### end Alembic commands ###
