"""first

Revision ID: a09eee37b58c
Revises:
Create Date: 2025-02-08 20:29:20.042584

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a09eee37b58c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "phone_number", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("service_policy_agreement", sa.Boolean(), nullable=False),
        sa.Column("privacy_policy_agreement", sa.Boolean(), nullable=False),
        sa.Column("third_party_information_agreement", sa.Boolean(), nullable=False),
        sa.Column(
            "nickname", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True
        ),
        sa.Column(
            "social_provider",
            sa.Enum("naver", "kakao", "anonymous", name="socialproviderenum"),
            nullable=False,
        ),
        sa.Column("joined_datetime", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
