"""empty message

Revision ID: b045424558d1
Revises: cc710029f24c
Create Date: 2025-03-06 11:33:13.918173

"""

from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b045424558d1"
down_revision: Union[str, None] = "cc710029f24c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_halls",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_halls", "name")
    # ### end Alembic commands ###
