"""empty message

Revision ID: d2699a4f3773
Revises: 26bc5ab385c7
Create Date: 2025-04-12 23:03:08.547497

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2699a4f3773"
down_revision: Union[str, None] = "26bc5ab385c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product_halls",
        "has_family_waiting_room",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "product_halls", "has_pyebaek_room", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "products",
        "address",
        existing_type=sa.VARCHAR(length=100),
        type_=sqlmodel.sql.sqltypes.AutoString(length=250),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "address",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=250),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "product_halls", "has_pyebaek_room", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "product_halls",
        "has_family_waiting_room",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    # ### end Alembic commands ###
