"""empty message

Revision ID: d5a81aea06b5
Revises: 2e31102ed46b
Create Date: 2025-03-08 16:46:22.303553

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a81aea06b5'
down_revision: Union[str, None] = '2e31102ed46b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklists', sa.Column('global_display_order', sa.Integer(), nullable=True))
    op.add_column('checklists', sa.Column('category_display_order', sa.Integer(), nullable=True))
    op.drop_column('checklists', 'display_order')
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('checklists', sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('checklists', 'category_display_order')
    op.drop_column('checklists', 'global_display_order')
    # ### end Alembic commands ###
