"""empty message

Revision ID: eba540576a0f
Revises: a96045f5b368
Create Date: 2025-06-28 21:05:33.643301

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eba540576a0f"
down_revision: Union[str, None] = "a96045f5b368"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "user_spents",
        sa.Column("deleted_datetime", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_spents", "deleted_datetime")

    # ### end Alembic commands ###
