"""empty message

Revision ID: eeabd1f3ad02
Revises: 43dbe204086d
Create Date: 2025-06-27 20:58:46.395979

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eeabd1f3ad02"
down_revision: Union[str, None] = "43dbe204086d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "news_categories", sa.Column("is_deleted", sa.Boolean(), nullable=False)
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news_categories", "is_deleted")
    # ### end Alembic commands ###
