"""empty message

Revision ID: eeb09c16b5e5
Revises: c131fcee85a0
Create Date: 2025-03-21 15:03:24.424045

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb09c16b5e5'
down_revision: Union[str, None] = 'c131fcee85a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_halls', 'max_capacity')
    op.drop_column('product_halls', 'hall_style')
    op.drop_column('product_halls', 'hall_type')
    op.drop_column('product_halls', 'wedding_type')
    op.drop_column('product_halls', 'min_capacity')
    op.drop_column('product_halls', 'wedding_running_time')
    op.drop_column('product_halls', 'food_cost')
    op.drop_column('product_halls', 'guaranteed_min_count')
    op.drop_column('product_halls', 'food_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_halls', sa.Column('food_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('product_halls', sa.Column('guaranteed_min_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product_halls', sa.Column('food_cost', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product_halls', sa.Column('wedding_running_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product_halls', sa.Column('min_capacity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product_halls', sa.Column('wedding_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('product_halls', sa.Column('hall_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('product_halls', sa.Column('hall_style', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('product_halls', sa.Column('max_capacity', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
