"""empty message

Revision ID: f0bfc31cb565
Revises: 5717cadd79c4
Create Date: 2025-03-05 15:22:05.696121

"""

from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f0bfc31cb565"
down_revision: Union[str, None] = "5717cadd79c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_categories", sa.Column("is_deleted", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "product_categories",
        sa.Column("created_datetime", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "product_categories",
        sa.Column("updated_datetime", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "product_categories",
        sa.Column("deleted_datetime", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_categories", "deleted_datetime")
    op.drop_column("product_categories", "updated_datetime")
    op.drop_column("product_categories", "created_datetime")
    op.drop_column("product_categories", "is_deleted")
    # ### end Alembic commands ###
